/**
 * AUTO-RESPONDER DATABASE INDEX
 * Basis data auto-responder bahasa Indonesia + gaul + slang + typo
 * Format: array of { keywords: string[], response: string }
 * Usage: import autoResponder from './auto-responder-index.js'
 */

const autoResponder = [

  // ─── SAPAAN & SALAM UMUM ───────────────────────────────────────────────────
  { keywords: ["halo", "helo", "hello", "hallo", "hellow", "helloo", "halooo", "helo bro", "halo bro"], response: "Halo! Ada yang bisa dibantu? 😊" },
  { keywords: ["hai", "hay", "hi", "hii", "hiii", "hiiii", "hay kak", "hai kak"], response: "Hai! Selamat datang! 👋" },
  { keywords: ["hey", "heyy", "heyyy", "heyyyy", "hey hey"], response: "Hey! Ada apa? 😄" },
  { keywords: ["assalamualaikum", "assalamualikum", "assalamualekum", "assalamualaikum wr wb", "aslm", "aslkm", "asskum", "askum", "ass"], response: "Wa'alaikumsalam warahmatullahi wabarakatuh! 🙏" },
  { keywords: ["waalaikumsalam", "walaikumsalam", "waalaikumsalam wr wb"], response: "Wa'alaikumsalam! 😊" },
  { keywords: ["selamat pagi", "met pagi", "pagi", "pagii", "pagiiii", "pagi kak", "selamat pg"], response: "Selamat pagi! Semoga harimu menyenangkan ☀️" },
  { keywords: ["selamat siang", "met siang", "siang", "siiang"], response: "Selamat siang! Sudah makan siang belum? 🍚" },
  { keywords: ["selamat sore", "met sore", "sore", "soree"], response: "Selamat sore! Jangan lupa istirahat ya 🌤️" },
  { keywords: ["selamat malam", "met malam", "malam", "malem", "malam kak", "malem kak"], response: "Selamat malam! Ada yang bisa dibantu? 🌙" },
  { keywords: ["selamat tengah malam", "tengah malam", "midnight"], response: "Masih on nih tengah malam 😄 Ada apa?" },
  { keywords: ["permisi", "permisi kak", "permisi min", "permisi gan", "permisi bro"], response: "Iya, ada yang bisa saya bantu?" },
  { keywords: ["excuse me", "excuse"], response: "Iya, ada yang perlu dibantu? 😊" },
  { keywords: ["oi", "oii", "oiii", "oy", "oyy"], response: "Oi! Ada apa? 😄" },
  { keywords: ["yo", "yoo", "yooo", "yo bro", "yo sis"], response: "Yo! Sup? 😎" },
  { keywords: ["hei", "heii", "heiii"], response: "Hei! Ada apa? 👋" },
  { keywords: ["p", "pp", "ping", "py"], response: "Ada apa? Silakan langsung tanya aja 😊" },
  { keywords: ["e", "eh", "ehh", "ehhh"], response: "Eh, ada yang bisa dibantu? 😄" },
  { keywords: ["om", "om halo", "om hai"], response: "Halo! Ada yang bisa dibantu? 😊" },
  { keywords: ["bos", "boss", "bosku", "bosssku"], response: "Halo bos! Ada yang bisa saya bantu? 🙏" },
  { keywords: ["kak", "kak halo", "kak hai", "kakak"], response: "Halo kak! Ada yang bisa dibantu? 😊" },
  { keywords: ["min", "min halo", "min hai", "admin"], response: "Halo! Ada yang bisa dibantu? 😊" },
  { keywords: ["gan", "gan halo", "agan", "agan halo"], response: "Halo gan! Ada yang bisa dibantu? 👍" },
  { keywords: ["bro", "bro halo", "bro hai", "brooo"], response: "Halo bro! Ada yang bisa dibantu? 😄" },
  { keywords: ["sis", "sis halo", "sis hai", "sisss"], response: "Halo sis! Ada yang bisa dibantu? 😊" },
  { keywords: ["sob", "sobat", "sobar"], response: "Halo sob! Ada apa? 😄" },
  { keywords: ["cuy", "cuyyy", "coy", "cok"], response: "Halo cuy! Ada yang bisa dibantu? 😄" },
  { keywords: ["gess", "ges", "gesss"], response: "Halo ges! Mau tanya apa? 😊" },
  { keywords: ["njir", "njirr", "anjir halo"], response: "Wkwk halo! Ada apa? 😄" },

  // ─── TANYA KABAR ──────────────────────────────────────────────────────────
  { keywords: ["apa kabar", "apa kabarnya", "gimana kabar", "bagaimana kabar", "kabar apa", "kabar gimana"], response: "Baik-baik aja nih, makasih udah nanya! Kamu gimana? 😊" },
  { keywords: ["how are you", "how r u", "how are u", "how r you", "how you doing", "how u doing"], response: "I'm doing great! Thanks for asking 😊 How about you?" },
  { keywords: ["sehat", "sehat ga", "sehat nggak", "sehat gak", "lagi sehat"], response: "Alhamdulillah sehat! Kamu juga semoga sehat ya 🙏" },
  { keywords: ["baik-baik saja", "baik baik saja", "baik saja", "baik aja"], response: "Syukurlah! Tetap jaga kesehatan ya 😊" },
  { keywords: ["lagi apa", "lagi ngapain", "lg ngapain", "lagi ngapain tuh", "ngapain sekarang", "ngapain skrg", "lagi sibuk"], response: "Lagi standby buat bantu kamu nih! Hehe 😄 Ada yang bisa dibantu?" },
  { keywords: ["gimana hari ini", "hari ini gimana", "hari ini how", "today how"], response: "Hari ini seru banget! Banyak yang nanya 😄 Kamu harinya gimana?" },
  { keywords: ["capek ga", "capek nggak", "capek gak", "lagi capek"], response: "Hehe ga capek kok! Siapin aja nanya, siap bantu 😊" },
  { keywords: ["bosen", "boring", "bete", "gabut", "gbt", "gabutin"], response: "Wah bosen? Sini cerita atau tanya sesuatu biar ga bosen 😄" },
  { keywords: ["nganggur", "nganggur nih", "lagi nganggur", "ga ada kerjaan", "gak ada kerjaan"], response: "Wkwk bareng dong! Mau ngobrol atau tanya apa? 😄" },
  { keywords: ["mau kemana", "mau ke mana", "kemana nih", "ke mana"], response: "Ke mana-mana juga siap! Hehe. Ada yang bisa dibantu? 😄" },
  { keywords: ["udah makan", "sudah makan", "makan dulu", "makan belum", "belum makan"], response: "Jangan lupa makan ya! Kesehatan itu penting 🍽️" },
  { keywords: ["udah tidur", "sudah tidur", "tidur belum", "belum tidur", "ga tidur", "gak tidur"], response: "Jangan begadang terus, istirahat yang cukup ya 😴" },
  { keywords: ["begadang", "begadang nih", "lagi begadang"], response: "Wah begadang? Jaga kesehatan ya, jangan terlalu sering 😅" },

  // ─── UCAPAN TERIMA KASIH ──────────────────────────────────────────────────
  { keywords: ["terima kasih", "makasih", "makasih ya", "thanks", "thank you", "thank u", "thx", "ty", "tq", "tengkyu", "tengkyuu", "tengkyu bgt", "mksh", "mkasih"], response: "Sama-sama! Senang bisa membantu 😊" },
  { keywords: ["terima kasih banyak", "makasih banyak", "thanks a lot", "thank you so much", "makasih banget", "mksh bgt"], response: "Sama-sama, dengan senang hati! 🙏" },
  { keywords: ["tengkyuu", "tenkyu", "thank youuu", "thanksss", "makasiiih"], response: "Hehe sama-sama yaaa! 😄🙏" },
  { keywords: ["mantap", "mantep", "mantabs", "mantul", "mantul bgt"], response: "Makasih! Semoga bermanfaat 😊" },
  { keywords: ["helpful", "membantu", "berguna", "bermanfaat"], response: "Senang bisa membantu! Jangan ragu tanya lagi ya 😊" },
  { keywords: ["oke deh", "oke makasih", "oke thanks", "ok thanks", "ok thx", "oke trims", "oke sip"], response: "Oke! Kalau ada yang perlu dibantu lagi, tanya aja ya 😊" },

  // ─── PERPISAHAN & PAMIT ───────────────────────────────────────────────────
  { keywords: ["sampai jumpa", "sampai jumpa lagi", "see you", "see u", "cu", "c u", "bye", "byee", "byeee", "seeyou"], response: "Sampai jumpa! Semoga harimu menyenangkan 👋" },
  { keywords: ["dadah", "dadah dah", "dah", "da", "daa"], response: "Dadah! Semoga harimu menyenangkan 👋😊" },
  { keywords: ["cabut", "cabut dulu", "mau cabut", "mo cabut"], response: "Oke, sampai jumpa! Semoga harinya menyenangkan 🙌" },
  { keywords: ["pamit", "mau pamit", "permisi pamit", "izin pamit"], response: "Oke, sampai jumpa! Hati-hati di jalan ya 🙏" },
  { keywords: ["duluan ya", "duluan deh", "aku duluan", "gue duluan"], response: "Oke, hati-hati ya! Sampai jumpa 👋" },
  { keywords: ["offline dulu", "off dulu", "afk dulu", "brb", "brb dulu"], response: "Oke, sampai jumpa! Jangan lama-lama ya hehe 😄" },
  { keywords: ["tidur dulu", "bobo dulu", "mau tidur", "mo tidur", "istirahat dulu"], response: "Selamat istirahat! Semoga tidurnya nyenyak 😴🌙" },
  { keywords: ["good night", "good nite", "selamat tidur", "met tidur", "gn", "gnight"], response: "Good night! Sweet dreams 🌙✨" },
  { keywords: ["good morning", "gm", "good morning bro"], response: "Good morning! Semoga harimu cerah ☀️" },

  // ─── SETUJU / TIDAK SETUJU ────────────────────────────────────────────────
  { keywords: ["oke", "ok", "okay", "okeh", "okelah", "oks", "okk", "okkk"], response: "Oke! Ada yang bisa dibantu lagi? 😊" },
  { keywords: ["siap", "siapp", "siaap", "siap bos", "siap kak", "siap gan"], response: "Siap! Kalau perlu bantuan lagi, tanya aja ya 💪" },
  { keywords: ["sip", "sipp", "sippp", "sip deh"], response: "Sip! Ada lagi yang mau ditanyain? 😄" },
  { keywords: ["betul", "bener", "benar", "bener bgt", "bener banget", "emang bener", "emang betul"], response: "Iya, betul! 😊" },
  { keywords: ["salah", "ga bener", "gak bener", "nggak bener", "kurang tepat"], response: "Maaf kalau ada yang kurang tepat! Boleh dikoreksi 🙏" },
  { keywords: ["setuju", "setuju bgt", "setuju banget", "agree", "agree bgt"], response: "Setuju! Kita sepemikiran 😄" },
  { keywords: ["tidak setuju", "gak setuju", "ga setuju", "nggak setuju", "disagree"], response: "Oke, boleh diskusi lebih lanjut! Apa yang kurang setuju? 😊" },
  { keywords: ["ya", "yaa", "yaaa", "yep", "yup", "yups", "yep bener"], response: "Iya! Ada lagi yang bisa dibantu? 😊" },
  { keywords: ["tidak", "nggak", "gak", "ga", "nope", "no", "nop"], response: "Oke, tidak apa-apa! Kalau ada yang mau ditanya, silakan 😊" },
  { keywords: ["mungkin", "kayaknya", "sepertinya", "maybe", "maybe iya", "maybe nggak"], response: "Hmm, mungkin iya atau mungkin tidak 😄 Ada info lebih lanjut yang bisa dibantu?" },
  { keywords: ["bisa", "bisa dong", "bisa ga", "bisa gak", "bisa nggak"], response: "Bisa! Apa yang mau dibantu? 😊" },
  { keywords: ["gapapa", "gpp", "ga papa", "gak papa", "tidak apa-apa", "no problem", "np"], response: "Oke, gapapa! Santai aja 😊" },

  // ─── EKSPRESI KAGET / HERAN ───────────────────────────────────────────────
  { keywords: ["wow", "woww", "wowww", "woow", "wah", "wahh", "wahhh"], response: "Wah seru ya! 😄 Ada cerita menarik?" },
  { keywords: ["gila", "gilaa", "gilaaa", "gila bgt", "gila banget"], response: "Wkwk gila gimana? Cerita dong! 😄" },
  { keywords: ["keren", "kerenn", "kerennn", "keren bgt", "keren banget"], response: "Iya keren kan! 😄 Ada yang mau ditanyain?" },
  { keywords: ["asik", "asikk", "asiikkk", "asyik", "asik bgt"], response: "Asik banget! Cerita lebih dong 😄" },
  { keywords: ["anjay", "anjayy", "anjir", "anjirr", "anjiir", "anjrit", "anjriiit"], response: "Wkwk emang gitu! Ada apa emangnya? 😄" },
  { keywords: ["astaga", "astaghfirullah", "astaghfirulloh", "astagfirullah"], response: "Astaghfirullah, ada apa? 😮" },
  { keywords: ["ya ampun", "ya alloh", "ya allah", "ya tuhan"], response: "Ada apa? Semoga semuanya baik-baik saja 🙏" },
  { keywords: ["serius", "serius ga", "serius gak", "serius nggak", "beneran", "beneran ga", "beneran gak", "srius"], response: "Serius! Hehe, ada yang mau diverifikasi? 😄" },
  { keywords: ["masa sih", "masa", "masa iya", "masa bener"], response: "Iya masa! Hehe beneran kok 😄" },
  { keywords: ["kok bisa", "gimana bisa", "kok gitu"], response: "Bisa aja! Mau tau caranya? 😄" },
  { keywords: ["impossible", "tidak mungkin", "ga mungkin", "gak mungkin"], response: "Hehe, mungkin aja kok! Yuk coba 😄" },
  { keywords: ["luar biasa", "luar biasaaa", "amazin", "amazing", "amazing bgt"], response: "Iya amazing banget kan! 😄" },
  { keywords: ["mantap jiwa", "mantap kali", "mantap lah"], response: "Mantap! Terus semangat ya 💪" },

  // ─── TERTAWA / CANDAAN ────────────────────────────────────────────────────
  { keywords: ["wkwk", "wkwkwk", "wkwkwkwk", "wkwkwkwkwk", "haha", "hahaha", "hahahaha", "hihi", "hihihi", "huhu", "huhuhu"], response: "Hahaha iya lucu kan! 😂" },
  { keywords: ["lol", "loll", "lolll", "LOL", "lmao", "LMAO", "lmaooo"], response: "Wkwkwk iya seru! 😂" },
  { keywords: ["lucu", "lucuu", "lucuuu", "lucu bgt", "lucu banget"], response: "Hahaha iya lucu! 😂 Mau cerita lucu lagi?" },
  { keywords: ["ngakak", "ngakakk", "ngakak parah", "gokil", "gokill", "gokilll"], response: "Wkwk iya ngakak parah! 😂😂" },
  { keywords: ["humor", "joke", "jokes", "bercanda", "candaan", "becanda"], response: "Hehe, suka humor juga nih! 😄 Mau denger cerita lucu?" },
  { keywords: ["lawak", "lawakan", "lelucon"], response: "Wkwkwk ada-ada aja! 😄" },
  { keywords: ["receh", "banyak receh", "receh amat"], response: "Hahaha emang receh! 😂😂" },
  { keywords: ["garing", "garingg", "garing bgt", "ga lucu", "gak lucu", "nggak lucu"], response: "Eh garing ya? Wkwkwk 😅 Nanti gue usahain yang lebih lucu!" },
  { keywords: ["ketawa", "ngetawain", "ngakak nih"], response: "Hehehe glad you're laughing! 😄" },
  { keywords: ["😂", "🤣", "😆", "😅"], response: "Hahaha! Ada yang lucu nih 😂" },
  { keywords: ["lmfao", "rofl", "xd", "XD", "xdd", "XDD"], response: "Wkwkwkwk! 😂😂" },
  { keywords: ["kwkwkw", "kwkwkwkw", "kkwwkk", "kwkw"], response: "Wkwkwk! 😂" },
  { keywords: ["hiks", "hikss", "huhu", "huhuu", "wkwkwk tapi sedih"], response: "Eh ada yang bikin sedih? Cerita dong 🥺" },

  // ─── MABAR (MAIN BARENG) & GAMING ─────────────────────────────────────────
  { keywords: ["mabar", "mbar", "main bareng", "main bareng yuk", "yuk mabar", "join mabar"], response: "Asik mabar! Game apa nih? 🎮" },
  { keywords: ["mabar ff", "mabar free fire", "free fire mabar", "ff mabar", "ff yuk"], response: "Siap mabar FF! Room ID berapa? 🔥" },
  { keywords: ["mabar ml", "mabar mobile legend", "mobile legend mabar", "ml mabar", "ml yuk", "mlbb mabar"], response: "Siap mabar ML! Rank atau classic? 🏆" },
  { keywords: ["mabar pubg", "pubg mabar", "pubg yuk"], response: "Siap mabar PUBG! Squad udah full belum? 🎯" },
  { keywords: ["mabar cod", "cod mabar", "call of duty mabar"], response: "Siap mabar COD! Mau mode apa? 🔫" },
  { keywords: ["mabar among us", "among us mabar"], response: "Among us yuk! Sus siapa dulu nih? 😏" },
  { keywords: ["mabar minecraft", "minecraft mabar"], response: "Minecraft yuk! Server apa yang dipakai? ⛏️" },
  { keywords: ["mabar valorant", "valorant mabar", "val mabar", "valo mabar"], response: "Valorant mabar! Rank berapa sekarang? 🔫" },
  { keywords: ["mabar genshin", "genshin mabar", "genshin impact mabar"], response: "Genshin mabar! Server apa? AR berapa? 🌟" },
  { keywords: ["mabar roblox", "roblox mabar"], response: "Roblox mabar! Game apa yang mau dimainkan? 🎮" },
  { keywords: ["rank", "ranknya", "rank berapa", "rank lo", "rank lu", "rank elu"], response: "Rank apa dulu nih? Biar disesuaikan strategi-nya! 🏆" },
  { keywords: ["noob", "nub", "newbie", "newb", "pemula"], response: "Hehe ga papa, semua juga pernah noob! Yang penting terus belajar 💪" },
  { keywords: ["pro", "pro player", "proplayer", "pro banget", "pro bgt"], response: "Wah pro! Bisa ajarin tips-nya dong 😄" },
  { keywords: ["carry", "di-carry", "dicarry", "carried", "minta di-carry"], response: "Wkwk minta dicarry! Semangat latihan ya biar bisa carry sendiri 💪" },
  { keywords: ["feeding", "feeder", "jangan feeding", "udah feeding"], response: "Jangan feeding nanti kena flame! Hati-hati ya 😅" },
  { keywords: ["push rank", "push ranked", "solo rank", "grind rank"], response: "Push rank? Semangat! Jangan lupa jaga mental ya 💪" },
  { keywords: ["gaming", "gamer", "gamers", "suka game", "hobi game", "main game"], response: "Gamer juga nih! Game favorit apa? 🎮" },
  { keywords: ["game apa", "main game apa", "rekomen game", "rekomendasi game"], response: "Tergantung genre yang disukai nih! Suka RPG, FPS, MOBA, atau casual? 🎮" },
  { keywords: ["lag", "lag bgt", "laggy", "koneksi jelek", "internet lemot"], response: "Wah lag, nyebelin ya! Coba restart router atau ganti ke WiFi/data yang lebih stabil 📶" },
  { keywords: ["dc", "disconnect", "kena dc", "kehapus", "drop"], response: "Duh kena DC! Cepet reconnect sebelum kena penalty 😅" },
  { keywords: ["cheat", "cheater", "hack", "hacker", "wallhack", "aimbot"], response: "Cheater emang nyebelin! Langsung report aja ya 🚫" },
  { keywords: ["report", "lapor", "report dia", "laporan"], response: "Langsung report aja! Biar kena ban hehe 😄" },
  { keywords: ["winrate", "win rate", "wr", "wr gue", "winrate gue"], response: "WR berapa? Yang penting terus improve ya! 📈" },
  { keywords: ["mvp", "MVP", "best player", "paling MVP"], response: "MVP! Keren banget! 🏆🔥" },
  { keywords: ["kalah", "kalahh", "kalah lagi", "sering kalah", "terus kalah"], response: "Jangan nyerah! Dari kekalahan kita bisa belajar banyak 💪" },
  { keywords: ["menang", "menang bro", "menang ges", "victory", "win", "winner"], response: "GG! Menang! 🎉🏆" },
  { keywords: ["gg", "GG", "gege", "gege wp"], response: "GG! Well played! 🎮✌️" },
  { keywords: ["wp", "WP", "well played", "wellplayed"], response: "Well played! Mantap! 👏" },
  { keywords: ["ez", "EZ", "gampang", "gampang bgt"], response: "EZ! Kece banget! 😎" },
  { keywords: ["clutch", "clutchhh", "keclutch", "ada yang clutch"], response: "Clutch keren banget! Jantungan ga tuh? 😱🔥" },
  { keywords: ["backdoor", "backdoorin", "mau backdoor"], response: "Backdoor! Main cantik! 😏" },
  { keywords: ["rampage", "maniac", "savage", "legendary", "godlike"], response: "RAMPAGE/SAVAGE! Gila, emang pro! 🔥🔥🔥" },
  { keywords: ["tournament", "turnamen", "ikut turnamen", "mau ikut turnamen"], response: "Wah ikut turnamen! Semangat! Persiapan udah mantap belum? 💪" },
  { keywords: ["esport", "e-sport", "esports", "karir esport"], response: "Esport sekarang lagi booming! Tetap semangat mengejar mimpi ya! 🏆" },

  // ─── TOXIC / FLAME ────────────────────────────────────────────────────────
  { keywords: ["bodoh", "bodo", "bodo amat", "bodoh kamu", "dasar bodoh"], response: "Eh, jangan kasar ya! Kita bisa diskusi dengan baik 😊" },
  { keywords: ["goblok", "goblog", "gblk", "dasar goblok"], response: "Hei, jaga kata-kata ya! Komunikasi yang baik itu penting 🙏" },
  { keywords: ["tolol", "tol*l", "dasar tolol"], response: "Tolong jaga bahasa ya, kita tetap saling menghormati 😊" },
  { keywords: ["idiot", "idiot kamu", "dasar idiot", "kamu idiot"], response: "Hei, jangan menghina ya! Kita bisa bicara dengan baik 😊" },
  { keywords: ["sial", "sialan", "dasar sial"], response: "Jaga kata-kata ya! Komunikasi yang baik itu lebih enak 😊" },
  { keywords: ["kampret", "dasar kampret"], response: "Eh, jangan kasar ya! 😊" },
  { keywords: ["bajingan", "brengsek", "dasar bajingan"], response: "Tolong jaga bahasa ya. Kita bisa ngobrol dengan sopan 🙏" },
  { keywords: ["tai", "taik", "brengsek"], response: "Jangan kasar-kasar ya! Semangat aja 😅" },
  { keywords: ["nyebelin", "nyebalin", "menyebalkan", "sebel"], response: "Aduh, ada yang bikin sebel ya? Cerita dong, siapa tau bisa bantu 😊" },
  { keywords: ["benci", "benciii", "aku benci", "gue benci", "saya benci"], response: "Aduh, kok benci? Ada apa emangnya? 🥺" },
  { keywords: ["jelek", "jeleekk", "jelek bgt", "jelek banget"], response: "Wah ada yang kurang memuaskan? Cerita dong, biar bisa diperbaiki 😊" },
  { keywords: ["payah", "payahh", "payah bgt", "payah deh"], response: "Hehe, apa yang bisa diperbaiki? Masukan sangat diterima 😊" },
  { keywords: ["lebay", "lebaaay", "lebay bgt", "ga lebay"], response: "Wkwk emang sedikit lebay! Tapi beneran kok hehe 😄" },
  { keywords: ["spam", "stop spam", "jangan spam", "ga usah spam"], response: "Maaf kalau mengganggu! Saya akan lebih tertib 🙏" },
  { keywords: ["toxic", "toxicc", "toxic bgt", "komunitas toxic"], response: "Jangan ikutan toxic ya! Kita jaga vibes-nya tetap positif 🌟" },
  { keywords: ["flame", "jangan flame", "stop flame", "flaming"], response: "Stop flame! Semua orang masih belajar kok 😊" },
  { keywords: ["chill", "calm down", "santai", "santai aja", "ga usah emosi"], response: "Iya, santai aja! Hehe 😄" },
  { keywords: ["emosi", "lagi emosi", "jangan emosi", "emosian"], response: "Tenang dulu ya, tarik napas panjang 😌" },
  { keywords: ["marah", "lagi marah", "marahh", "kamu marah"], response: "Ada yang bikin marah? Cerita dulu, siapa tau bisa bantu 😊" },

  // ─── CURHAT & PERASAAN ────────────────────────────────────────────────────
  { keywords: ["galau", "galauuu", "lagi galau", "galau bgt", "galau banget"], response: "Eh, lagi galau? Cerita dong, jangan disimpen sendiri 🤗" },
  { keywords: ["sedih", "sadih", "sad", "lagi sedih", "sedih bgt", "sedih banget"], response: "Aduh, kok sedih? Ada apa? Cerita ya, aku dengerin 🥺💙" },
  { keywords: ["nangis", "mau nangis", "pengen nangis", "nangis nih"], response: "Eh jangan nangis! Ada apa? Boleh cerita, aku dengerin kok 🤗" },
  { keywords: ["bahagia", "senang", "happy", "gembira", "lagi bahagia"], response: "Wah, bahagia itu menular! Ada berita bagus apa? 😄🎉" },
  { keywords: ["stress", "stres", "tertekan", "lagi stress", "burnout"], response: "Aduh, stress ya? Ambil napas panjang dulu. Kalau mau cerita, aku dengerin 🤗" },
  { keywords: ["mager", "lagi mager", "males gerak", "malas gerak"], response: "Hehe mager! Sebangun-bangunnya semangat ya! 😄" },
  { keywords: ["males", "malas", "malasnya", "males bgt", "males banget"], response: "Hehe, kadang emang butuh rehat. Tapi jangan lama-lama ya! 😊" },
  { keywords: ["kangen", "kangen bgt", "kangeenn", "lagi kangen"], response: "Aww, lagi kangen ya? Segera ketemu ya sama yang dirindukan 🤗" },
  { keywords: ["kesepian", "sepi", "sepinya", "lagi sepi", "sendirian"], response: "Aduh, kok kesepian? Sini ngobrol sama aku deh! 😊" },
  { keywords: ["takut", "takutt", "ketakutan", "lagi takut"], response: "Tenang aja! Aku di sini. Ada yang bikin takut? Cerita dong 🤗" },
  { keywords: ["khawatir", "was was", "cemas", "gelisah", "anxiety"], response: "Jangan khawatir berlebihan ya! Fokus pada hal yang bisa dikontrol 🙏" },
  { keywords: ["putus asa", "nyerah", "mau menyerah", "menyerah"], response: "Jangan menyerah! Setiap masalah pasti ada jalan keluarnya 💪" },
  { keywords: ["lelah", "capek", "kecapean", "exhausted", "kelelahan"], response: "Istirahat dulu ya! Kesehatan itu paling penting 😊" },
  { keywords: ["overthinking", "overthink", "kebanyakan pikir", "terlalu mikirin"], response: "Jangan overthinking! Tarik napas, focus ke hal-hal positif 😊" },
  { keywords: ["insomnia", "ga bisa tidur", "gak bisa tidur", "sulit tidur"], response: "Aduh, insomnia? Coba relaksasi dulu, hindari gadget sebelum tidur 😴" },
  { keywords: ["broken heart", "patah hati", "sakit hati", "ditinggal", "diputusin", "putus"], response: "Eh, sabar ya. Patah hati itu memang menyakitkan, tapi pasti berlalu 💙" },
  { keywords: ["jomblo", "single", "lagi single", "masih jomblo"], response: "Jomblo happy juga lho! Nikmatin dulu waktu untuk diri sendiri 😄" },
  { keywords: ["gebetan", "crush", "naksir", "suka sama", "ada rasa"], response: "Wah ada gebetan nih! Udah PDKT belum? 😏" },
  { keywords: ["pdkt", "pendekatan", "nembak", "confess", "mau nembak"], response: "Semangat PDKT! Jangan takut ditolak, yang penting berani! 💪😄" },
  { keywords: ["dtjn", "ditolak", "ditolak gebetan", "ditolak crush"], response: "Aduh, ditolak ya? Gapapa! Masih banyak kesempatan lain 💙" },

  // ─── PERTANYAAN UMUM ──────────────────────────────────────────────────────
  { keywords: ["siapa kamu", "kamu siapa", "lo siapa", "elu siapa", "km siapa"], response: "Aku bot auto-responder yang siap membantu kamu 24/7! 🤖" },
  { keywords: ["apa itu", "apaan nih", "ini apa", "maksudnya apa", "artikan"], response: "Mau tanya tentang apa? Boleh lebih spesifik 😊" },
  { keywords: ["kenapa", "kenap", "why", "mengapa", "kok gitu", "kok bisa"], response: "Kenapa ya? Bisa cerita lebih detail? 🤔" },
  { keywords: ["bagaimana", "gimana caranya", "cara gimana", "how to", "howto"], response: "Caranya gimana ya? Bisa kasih tau lebih detailnya? 😊" },
  { keywords: ["dimana", "di mana", "where", "lokasinya", "tempatnya"], response: "Lokasinya di mana ya? Bisa kasih info lebih detail? 📍" },
  { keywords: ["kapan", "when", "waktunya kapan", "kapan bisa"], response: "Kapan ya? Tergantung situasi dan kondisinya 😊" },
  { keywords: ["berapa", "harga berapa", "harganya", "cost", "biaya", "total"], response: "Berapa ya? Perlu detail lebih lanjut untuk bisa jawab akurat 😊" },
  { keywords: ["boleh", "bolehkah", "bisa ga", "bisa nggak", "izin"], response: "Boleh! Silakan, tidak ada masalah 😊" },
  { keywords: ["tolong", "minta tolong", "bantu", "bantuiin", "bantuin"], response: "Iya, saya siap membantu! Apa yang perlu dibantu? 🙏" },
  { keywords: ["tips", "trik", "trick", "cara", "tutorial", "panduan"], response: "Mau tips tentang apa? Kasih tau dulu topiknya! 😊" },
  { keywords: ["rekomendasi", "rekomen", "saran", "suggest", "recommendation"], response: "Mau rekomendasi apa? Cerita dulu kebutuhannya 😊" },
  { keywords: ["info", "informasi", "infonya", "ada info"], response: "Mau info tentang apa? Silakan tanya! 😊" },

  // ─── UNGKAPAN POPULER / TRENDING ──────────────────────────────────────────
  { keywords: ["yakin", "yakin bro", "yakin ga", "yakin nggak", "yakin nih"], response: "Yakin 100%! Hehe 😄" },
  { keywords: ["skip", "skip deh", "lewatin", "ga usah"], response: "Oke skip! Lanjut ke topik lain? 😄" },
  { keywords: ["ntar", "nanti", "later", "tar aja", "besok aja"], response: "Jangan nanti-nanti terus ya! Hehe 😄" },
  { keywords: ["beneran", "serius beneran", "beneran nih", "jujur"], response: "Beneran kok! Hehe, ada yang mau dicek lagi? 😊" },
  { keywords: ["kecewa", "kecewaa", "kecewa bgt", "disappointed"], response: "Aduh, kok kecewa? Ada yang salah? Cerita dong 🥺" },
  { keywords: ["ngerti", "paham", "mudeng", "ngerti deh", "aku ngerti"], response: "Bagus kalau udah ngerti! Ada yang mau ditanyain lagi? 😊" },
  { keywords: ["ga ngerti", "gak ngerti", "nggak ngerti", "bingung", "bingun", "confused"], response: "Gapapa kalau bingung! Mau dijelasin pelan-pelan? 😊" },
  { keywords: ["ribet", "ribet bgt", "ribet banget", "complicated"], response: "Kedengarannya emang ribet ya! Tapi pasti bisa dipahami kok 😊" },
  { keywords: ["simple", "simpel", "gampang", "mudah", "easy"], response: "Iya, simple banget kan! 😄" },
  { keywords: ["woles", "santuy", "santai", "relax", "relaxs", "coolly"], response: "Woles! Santuy aja bro 😎" },
  { keywords: ["lebay", "keberlebihan", "dramatis", "drama"], response: "Wkwkwk emang drama queen/king nih! 😄" },
  { keywords: ["gaskeun", "gaspol", "gas", "gas bro", "gassss"], response: "GAS! LET'S GO! 🚀💪" },
  { keywords: ["ngegas", "nge-gas", "gaspol bro"], response: "Wkwk ngegas! GAS TERUS! 🔥" },
  { keywords: ["parah", "parahh", "parah bgt", "parah banget"], response: "Parah emang! 😄 Ada apa emangnya?" },
  { keywords: ["epic", "epicc", "epik", "epic bgt", "super epic"], response: "EPIC! Gokil banget! 🔥🔥" },
  { keywords: ["aesthetic", "estetik", "aestheticc", "kece"], response: "Iya aesthetic banget! 😍" },
  { keywords: ["bucin", "bucinnya", "lagi bucin", "bucin mode on"], response: "Wkwk bucin mode on ya! 😄 Tapi jangan sampai kebablasan ya!" },
  { keywords: ["absurd", "absurdd", "ga masuk akal", "gak masuk akal"], response: "Haha iya absurd! Tapi seru kan? 😄" },
  { keywords: ["random", "randomm", "acak", "ga nyambung", "gak nyambung"], response: "Wkwk random banget! 😄" },
  { keywords: ["julid", "nyinyir", "nyinyirin", "suka julid"], response: "Hehe jangan terlalu julid ya! Semua orang punya kelebihan masing-masing 😊" },
  { keywords: ["kepo", "kepoo", "kepo bgt", "penasaran bgt"], response: "Kepo ya? Haha iya boleh kepo sedikit! 😄" },
  { keywords: ["fomo", "ketinggalan", "takut ketinggalan"], response: "FOMO emang nyata! Tapi tenang, ga semua hal perlu diikutin kok 😊" },
  { keywords: ["healing", "butuh healing", "perlu healing", "mau healing"], response: "Healing dulu yuk! Recharge energi itu penting 🌿😌" },
  { keywords: ["vibes", "vibesnya", "good vibes", "bad vibes"], response: "Semangat jaga good vibes ya! 🌟" },
  { keywords: ["aura", "aura positif", "aura keren", "aura gaming"], response: "Jaga aura tetap positif! 🌟" },
  { keywords: ["starterpack", "starter pack", "ciri-ciri", "tanda-tanda"], response: "Wkwk iya tuh starter pack-nya! 😄" },
  { keywords: ["nolep", "kurang gaul", "ga gaul", "gak gaul"], response: "Hehe gapapa nolep, asalkan bahagia! 😄" },
  { keywords: ["genz", "gen z", "generasi z", "anak jaman now"], response: "Gen Z emang seru-seru ya! 😄" },
  { keywords: ["millenial", "milenial", "generasi milenial"], response: "Millennial juga keren kok! Setiap generasi punya keunikannya sendiri 😊" },
  { keywords: ["old school", "oldschool", "jadul", "jadoel", "kolot"], response: "Old school tapi classic! Vintage vibes 😄" },
  { keywords: ["hits", "viral", "trending", "lagi viral", "lagi hits", "sedang viral"], response: "Iya lagi viral banget nih! Udah tau belum? 😄" },
  { keywords: ["kuy", "kuyy", "ku yuk", "yuk kuy"], response: "KUY! Let's go! 🚀" },
  { keywords: ["wkwkland", "wkwk land", "republic wkwk"], response: "WKWKWKLAND! Proud to be Indonesian! 🇮🇩😄" },

  // ─── SINGKATAN & AKRONIM ──────────────────────────────────────────────────
  { keywords: ["btw", "BTW", "by the way"], response: "BTW ya? Ada apa? 😄" },
  { keywords: ["fyi", "FYI", "for your information"], response: "FYI ya, makasih infonya! 😊" },
  { keywords: ["imo", "IMO", "imho", "IMHO", "in my opinion"], response: "IMO, itu tergantung situasinya juga sih 😊" },
  { keywords: ["tbh", "TBH", "to be honest", "jujur aja"], response: "TBH, aku setuju! 😄" },
  { keywords: ["ngl", "NGL", "not gonna lie"], response: "NGL, itu emang bener! 😄" },
  { keywords: ["smh", "SMH", "shaking my head"], response: "Smh iya, bisa gitu ya 😅" },
  { keywords: ["afaik", "AFAIK", "as far as i know"], response: "AFAIK, itu bener kok! Tapi bisa dicek lagi 😊" },
  { keywords: ["irl", "IRL", "in real life", "di dunia nyata"], response: "Di IRL kadang beda ya sama online! 😄" },
  { keywords: ["dm", "DM", "direct message", "inbox", "pm", "PM", "private message"], response: "DM aja langsung ya kalau mau private! 😊" },
  { keywords: ["otw", "OTW", "on the way", "lagi otw", "udah otw"], response: "OTW! Tunggu ya 😄" },
  { keywords: ["wfh", "WFH", "work from home", "kerja dari rumah"], response: "WFH! Semangat kerja dari rumah ya! 🏠💻" },
  { keywords: ["wfo", "WFO", "work from office", "kerja dari kantor"], response: "WFO! Semangat ke kantor ya! 🏢" },
  { keywords: ["ootd", "OOTD", "outfit of the day"], response: "OOTD kece bgt! 😍" },
  { keywords: ["asap", "ASAP", "as soon as possible", "sesegera mungkin", "buru-buru"], response: "ASAP ya, siap! 🚀" },
  { keywords: ["bts", "BTS", "behind the scene", "behind the scenes"], response: "BTS (behind the scenes) atau BTS (boyband)? Hehe 😄" },
  { keywords: ["q", "qu", "gue", "gw", "gua", "aku", "saya"], response: "Oh iya! Gimana? 😊" },
  { keywords: ["u", "lu", "lo", "elu", "kamu", "km", "kmu", "anda"], response: "Oh iya, ada yang bisa dibantu? 😊" },
  { keywords: ["yg", "yang"], response: "Yang mana? Bisa lebih spesifik? 😊" },
  { keywords: ["dg", "dgn", "dengan"], response: "Dengan siapa atau apa? 😊" },
  { keywords: ["utk", "untuk"], response: "Untuk apa? 😊" },
  { keywords: ["dr", "dari"], response: "Dari mana? 😊" },
  { keywords: ["ke", "kpd", "kepada"], response: "Kepada siapa? 😊" },
  { keywords: ["bbrp", "beberapa"], response: "Beberapa ya, berapa tepatnya? 😊" },
  { keywords: ["jg", "juga"], response: "Oh juga ya! 😊" },
  { keywords: ["sdh", "udah", "sudah"], response: "Sudah? Bagaimana hasilnya? 😊" },
  { keywords: ["blm", "belum"], response: "Belum? Kenapa? 😊" },
  { keywords: ["gt", "gitu", "gituu", "gitu ya"], response: "Gitu ya? Oke! 😊" },
  { keywords: ["ini", "itu", "ini nih", "itu nih"], response: "Ini/itu apa ya? Bisa dijelaskan lebih? 😊" },
  { keywords: ["tp", "tapi", "tapi ya", "tapi deh"], response: "Tapi apa? Lanjut dong! 😊" },
  { keywords: ["klo", "kl", "kalo", "kalau", "kalau gitu"], response: "Kalau gitu gimana? 😊" },
  { keywords: ["trz", "trs", "terus", "lanjut", "trus"], response: "Terus? Lanjutin ceritanya! 😊" },
  { keywords: ["emg", "emang", "emangnya", "memang"], response: "Emang gitu ya! 😄" },
  { keywords: ["bngt", "bgt", "banget", "beneran banget"], response: "Iya banget! 😊" },
  { keywords: ["lg", "lagi", "lgi", "sedang"], response: "Lagi apa nih? 😊" },
  { keywords: ["prn", "pernah", "pernahn"], response: "Pernah? Kapan? 😊" },

  // ─── TYPO UMUM ────────────────────────────────────────────────────────────
  { keywords: ["helo", "heloo", "hellp", "hell0"], response: "Halo! Ada yang bisa dibantu? 😊" },
  { keywords: ["slamat pg", "slamat pagi", "slmt pagi", "slm pagi"], response: "Selamat pagi! Semoga harimu menyenangkan ☀️" },
  { keywords: ["slamat mlm", "slmt mlm", "slm malam"], response: "Selamat malam! 🌙" },
  { keywords: ["mksh", "mksih", "mksih ya", "mksh ya", "mkasih"], response: "Sama-sama! 😊" },
  { keywords: ["trims", "trimakasih", "trimksih", "trmksh"], response: "Sama-sama! Senang bisa membantu 🙏" },
  { keywords: ["ap kbr", "apa kbr", "kbr apa"], response: "Baik-baik aja! Kamu gimana? 😊" },
  { keywords: ["gimna", "giamna", "gmna", "gimna nih"], response: "Gimana? Ada yang bisa dibantu? 😊" },
  { keywords: ["kenpa", "knp", "knpa", "kenap"], response: "Kenapa ya? Cerita dong! 😊" },
  { keywords: ["dmna", "dmn", "d mana", "dimna"], response: "Di mana ya? 📍" },
  { keywords: ["kapn", "kpn", "kapan nih", "kapn ya"], response: "Kapan ya? Tergantung situasi 😊" },
  { keywords: ["siap kk", "sip kk", "oke kk", "ok kk"], response: "Sip! Kalau perlu bantuan lagi, tanya ya 😊" },
  { keywords: ["slm kenal", "slam kenal", "salam knal", "slm knal"], response: "Salam kenal juga! Senang berkenalan 😊" },
  { keywords: ["met knal", "mt knal", "met kenal", "mw knal"], response: "Met kenal juga! Halo! 😊👋" },
  { keywords: ["makasihhh", "makasiiih", "mkasiih", "mkasiihh"], response: "Hehe, sama-sama ya! 😊🙏" },
  { keywords: ["ohok", "oke deh haha", "ohke", "ohkke"], response: "Oke! Ada lagi yang mau ditanyain? 😄" },
  { keywords: ["siipp", "sipppp", "siiiip", "sippp"], response: "Sip! Mantap! 👍" },
  { keywords: ["bner", "bnar", "bnr", "benerr"], response: "Bener! 😊" },
  { keywords: ["gabisa", "ga bsa", "ngga bisa", "gak bisa"], response: "Gapapa kalau belum bisa! Pasti ada jalan keluarnya 😊" },
  { keywords: ["nanya", "nanyain", "pengen nanya", "mau nanya"], response: "Iya, silakan nanya! Aku siap jawab 😊" },
  { keywords: ["udh", "udah deh", "udah ya"], response: "Oke, udah! Ada lagi? 😊" },
  { keywords: ["blom", "blum", "belm", "belom"], response: "Oh belum? Oke, kalau udah siap silakan tanya 😊" },
  { keywords: ["dng", "dngan", "dngen"], response: "Dengan apa/siapa? 😊" },
  { keywords: ["sbnrnya", "sbenernya", "sebenarnya ya"], response: "Sebenarnya gimana? Cerita dong! 😊" },
  { keywords: ["kynya", "kayanya", "kayaknya ya"], response: "Kayaknya gimana nih? 😊" },
  { keywords: ["mgkn", "mungkn", "mungkin ya"], response: "Mungkin saja! 😊" },
  { keywords: ["bgt jg", "banget juga", "bngt jg"], response: "Iya banget! 😄" },
  { keywords: ["msh", "masih", "msih"], response: "Masih apa nih? 😊" },
  { keywords: ["smpe", "sampe", "sampai", "sampe deh"], response: "Sampai kapan? 😊" },
  { keywords: ["lngsg", "langsung aja", "langsung deh"], response: "Langsung aja! Gaskeun! 🚀" },
  { keywords: ["krna", "karna", "karena nih", "soalnya"], response: "Karena apa? Cerita dong! 😊" },
  { keywords: ["jdi", "jadi", "jdnya"], response: "Jadi gimana hasilnya? 😊" },

  // ─── RESPON BOT / OTOMATIS ────────────────────────────────────────────────
  { keywords: ["bot", "ini bot", "kamu bot", "lo bot", "robot"], response: "Iya, aku bot auto-responder! Siap membantu 24/7 🤖✨" },
  { keywords: ["ada orang", "ada manusia", "beneran manusia", "manusia ga"], response: "Aku bot otomatis! Tapi siap bantu sepenuh hati 🤖😊" },
  { keywords: ["auto reply", "auto response", "auto responder", "otomatis"], response: "Yap, ini auto-responder! Siap 24/7 untuk kamu 🤖" },
  { keywords: ["ai", "artificial intelligence", "kecerdasan buatan", "machine learning"], response: "Iya, aku berbasis AI! Hehe 🤖✨" },
  { keywords: ["siap melayani", "siap bantu", "ready to help"], response: "Siap! Selalu siap melayani 24 jam 🙏" },
  { keywords: ["ga aktif", "offline", "status offline", "ga online"], response: "Bot ini aktif 24 jam! Tidak pernah offline 🤖" },
  { keywords: ["error", "eror", "error nih", "ada error"], response: "Aduh ada error? Coba refresh atau hubungi admin ya 🔧" },
  { keywords: ["bug", "ada bug", "kayanya ada bug"], response: "Wah ada bug? Laporan ke admin ya biar bisa diperbaiki! 🐛" },
  { keywords: ["update", "versi terbaru", "new update", "ada update"], response: "Update terbaru sudah tersedia! Cek fitur barunya 🆕✨" },
  { keywords: ["maintenance", "down", "server down", "lagi maintenance"], response: "Maaf, sedang ada maintenance! Akan segera normal kembali 🔧" },
  { keywords: ["loading", "lagi loading", "loading lama", "lemot"], response: "Sabar ya, sedang diproses 😊 Tunggu sebentar!" },
  { keywords: ["ping", "cek ping", "latency", "koneksi"], response: "Pong! Koneksi aktif ✅" },
  { keywords: ["tes", "test", "testing", "coba", "cek cek"], response: "Tes berhasil! Semua berjalan normal ✅" },
  { keywords: ["aktif", "masih aktif", "online", "lagi online"], response: "Aktif 24/7! Siap melayani kapan saja 🤖✨" },

  // ─── TOPIK SEHARI-HARI ────────────────────────────────────────────────────
  { keywords: ["cuaca", "cuaca hari ini", "cuaca gimana", "panas", "dingin", "hujan"], response: "Wah soal cuaca, cek aplikasi weather di hpmu ya untuk info akurat! ☀️🌧️" },
  { keywords: ["makan apa", "makan siang apa", "makan malam apa", "menu hari ini", "sarapan apa"], response: "Makan apa ya? Yang penting sehat dan bergizi! 🍚😄" },
  { keywords: ["lapar", "laper", "laper bgt", "perut lapar", "kelaparan"], response: "Aduh lapar! Buruan makan dulu ya biar tetap semangat 🍽️" },
  { keywords: ["kopi", "ngopi", "minum kopi", "kopi dulu", "pengen kopi"], response: "Kopi dulu bro! Biar semangat! ☕😄" },
  { keywords: ["teh", "minum teh", "teh hangat", "teh dulu"], response: "Teh hangat emang enak! Apalagi sambil santai 🍵😊" },
  { keywords: ["jajan", "pengen jajan", "mau jajan", "jajan apa"], response: "Mau jajan apa? Jangan lupa pilih yang sehat juga ya! 😄" },
  { keywords: ["nonton", "nonton apa", "film apa", "drama apa", "anime apa"], response: "Lagi nonton apa? Kasih rekomendasi dong! 🎬" },
  { keywords: ["musik", "dengerin musik", "playlist", "lagu apa", "lagu bagus"], response: "Musik apa yang lagi disukain? Boleh share playlist-nya! 🎵" },
  { keywords: ["baca", "baca buku", "buku apa", "novel apa", "komik apa"], response: "Lagi baca apa? Boleh kasih rekomendasi buku! 📚" },
  { keywords: ["olahraga", "gym", "lari", "fitness", "sport"], response: "Semangat olahraga! Tubuh sehat mental kuat 💪😄" },
  { keywords: ["shopping", "belanja", "belanja apa", "mau belanja"], response: "Belanja apa nih? Hati-hati impulsive buying! 😄🛍️" },
  { keywords: ["liburan", "vacation", "holiday", "mau liburan", "rencana liburan"], response: "Wah liburan! Mau ke mana? 😄✈️" },
  { keywords: ["traveling", "travel", "jalan-jalan", "trip"], response: "Asik jalan-jalan! Destinasi favorit kamu di mana? 🗺️" },
  { keywords: ["sekolah", "kuliah", "kampus", "kelas", "belajar"], response: "Semangat belajar! Ilmu itu investasi terbaik 📚💪" },
  { keywords: ["ujian", "UTS", "UAS", "exam", "test", "ulangan"], response: "Semangat ujiannya! Belajar yang rajin ya 📖💪" },
  { keywords: ["PR", "tugas", "homework", "deadline", "deadline besok"], response: "Aduh deadline! Semangat ngerjainnya, pasti bisa! 💪📝" },
  { keywords: ["kerja", "kerjaan", "pekerjaan", "kantor", "office"], response: "Semangat kerja! Produktif selalu ya 💼💪" },
  { keywords: ["gajian", "gaji", "salary", "bonus"], response: "Wah gajian! Jangan lupa ditabung ya, hehe 😄💰" },
  { keywords: ["uang", "duit", "money", "cash", "keuangan"], response: "Soal keuangan, kelola dengan bijak ya! 💰😊" },
  { keywords: ["nabung", "menabung", "tabungan", "saving", "investasi"], response: "Semangat nabung! Masa depan cerah menanti 💰🌟" },
  { keywords: ["utang", "hutang", "pinjam", "pinjaman", "cicilan"], response: "Hati-hati masalah utang ya! Sesuaikan dengan kemampuan 🙏" },
  { keywords: ["diet", "diet ketat", "mau diet", "lagi diet"], response: "Semangat diet! Tapi jangan terlalu keras sama diri sendiri ya 😊" },
  { keywords: ["berat badan", "BB", "timbang", "naik BB", "turun BB"], response: "Jaga kesehatan ya! Yang penting badan sehat dan fit 💪" },
  { keywords: ["sakit", "lagi sakit", "ga enak badan", "demam", "flu", "batuk", "pilek"], response: "Aduh lagi sakit? Istirahat yang banyak dan minum obat ya! Semoga cepat sembuh 🙏💊" },
  { keywords: ["dokter", "ke dokter", "periksa dokter", "medical", "rumah sakit"], response: "Jangan tunda ke dokter ya kalau merasa tidak enak badan! Kesehatan itu penting 🏥" },
  { keywords: ["vaksin", "vaksinasi", "vaksid", "sudah vaksin", "belum vaksin"], response: "Vaksin itu penting untuk kesehatan dan keselamatan bersama 💉🙏" },

  // ─── HOBI & MINAT ────────────────────────────────────────────────────────
  { keywords: ["hobi", "hobi apa", "hobinya apa", "hobi kamu", "suka apa"], response: "Hobi apa? Cerita dong, pasti seru! 😊" },
  { keywords: ["suka kucing", "punya kucing", "cat lover", "anak kucing", "kucing imut"], response: "Kucing emang menggemaskan! 🐱 Sudah dikasih nama belum?" },
  { keywords: ["suka anjing", "punya anjing", "dog lover", "anak anjing"], response: "Anjing lucu banget! 🐶 Ras apa yang dipelihara?" },
  { keywords: ["suka ikan", "punya ikan", "aquarium", "ikan hias"], response: "Ikan juga seru dipelihara! 🐟 Aquarium-nya cantik?" },
  { keywords: ["berkebun", "tanam tanaman", "tanaman hias", "menanam"], response: "Berkebun itu menenangkan ya! 🌱 Tanaman apa yang dipelihara?" },
  { keywords: ["fotografi", "photography", "foto-foto", "suka fotografi"], response: "Fotografi keren! 📷 Pakai kamera apa?" },
  { keywords: ["melukis", "menggambar", "drawing", "painting", "sketsa"], response: "Wah seniman nih! 🎨 Boleh show hasilnya dong!" },
  { keywords: ["menulis", "nulis", "writing", "penulis", "ngeblog", "blog"], response: "Menulis itu keren! ✍️ Nulis tentang apa biasanya?" },
  { keywords: ["memasak", "masak", "cooking", "resep", "chef"], response: "Wah bisa masak! 👨‍🍳 Masak apa yang jadi andalannya?" },
  { keywords: ["baking", "bikin kue", "kue", "roti", "cake"], response: "Baking seru banget! 🎂 Kue favorit bikin apa?" },
  { keywords: ["crafting", "kerajinan", "DIY", "handmade", "rajut", "sulam"], response: "Handmade selalu spesial! 🧶 Lagi bikin apa?" },
  { keywords: ["cosplay", "cosplayer", "kostum", "costume"], response: "Cosplay keren banget! 🎭 Karakter favorit siapa?" },
  { keywords: ["nyanyi", "menyanyi", "karaoke", "vokal", "bernyanyi"], response: "Suka nyanyi! 🎤 Genre musik apa yang sering dinyanyiin?" },
  { keywords: ["main musik", "gitar", "piano", "drum", "violin", "biola", "bass"], response: "Wah musisi nih! 🎸 Sudah berapa lama main musiknya?" },
  { keywords: ["dance", "menari", "ngedance", "dancing", "tarian"], response: "Dance keren! 💃 Genre dance apa yang dikuasain?" },

  // ─── SOSIAL MEDIA & INTERNET ──────────────────────────────────────────────
  { keywords: ["instagram", "ig", "IG", "insta"], response: "Instagram? Follow-follow-an yuk! 📸😄" },
  { keywords: ["tiktok", "tik tok", "konten tiktok", "fyp"], response: "TikTok! Kontennya seru-seru ya! 🎵📱" },
  { keywords: ["youtube", "YT", "yt", "nonton youtube", "konten youtube"], response: "YouTube! Channel favorit kamu apa? 🎬" },
  { keywords: ["twitter", "X", "ngetweet", "cuitan"], response: "Twitter/X! Lagi trending apa nih? 🐦" },
  { keywords: ["facebook", "fb", "FB", "fbi", "meta"], response: "Facebook! Masih aktif juga ya! 👍" },
  { keywords: ["discord", "server discord", "join discord"], response: "Discord! Ada server seru? Share dong invite-nya! 🎮" },
  { keywords: ["telegram", "TG", "tg", "grup telegram"], response: "Telegram! Fitur-fiturnya makin lengkap ya 📱" },
  { keywords: ["whatsapp", "WA", "wa", "pesan WA", "grup wa"], response: "WhatsApp! Medium komunikasi utama nih hehe 📱" },
  { keywords: ["line", "line app", "pesan line"], response: "LINE! Klasik tapi masih dipakai 😄" },
  { keywords: ["pinterest", "pin", "inspirasi"], response: "Pinterest untuk inspirasi! Aesthetic banget 📌✨" },
  { keywords: ["linkedin", "professional", "networking"], response: "LinkedIn! Networking profesional nih! 💼" },
  { keywords: ["viral", "trending", "fyp", "for you page"], response: "Viral banget! Udah nonton belum? 😄" },
  { keywords: ["followers", "follower", "subscriber", "sub"], response: "Mau nambah followers? Konsisten konten ya! 📈" },
  { keywords: ["konten", "content", "bikin konten", "content creator"], response: "Content creator keren! Konten apa yang biasanya dibuat? 📸" },
  { keywords: ["livestream", "live", "live streaming", "siaran langsung"], response: "Live stream! Seru ya bisa interaksi langsung sama penonton 🎥" },
  { keywords: ["podcast", "dengerin podcast", "bikin podcast"], response: "Podcast keren! Topik apa yang dibahas? 🎙️" },
  { keywords: ["meme", "memes", "bikin meme", "kirim meme"], response: "Meme terbaik selalu bikin ngakak! 😂 Share dong!" },
  { keywords: ["stalker", "stalkin", "stalk", "stalking"], response: "Hati-hati stalking privasi orang ya! 😅" },
  { keywords: ["reels", "shorts", "video pendek", "short video"], response: "Reels/Shorts memang addictive ya! 😄" },

  // ─── MOTIVASI & INSPIRASI ─────────────────────────────────────────────────
  { keywords: ["semangat", "semangaat", "semngat", "fighting", "fighting bro"], response: "SEMANGAT! Kamu pasti bisa! 💪🔥" },
  { keywords: ["jangan menyerah", "jangan nyerah", "ga boleh nyerah"], response: "Jangan pernah menyerah! Setiap usaha pasti ada hasilnya 💪" },
  { keywords: ["keep going", "keep it up", "terus semangat", "tetap semangat"], response: "Keep going! Kamu sudah sejauh ini, jangan berhenti! 🚀" },
  { keywords: ["motivasi", "butuh motivasi", "kasih motivasi", "kurang semangat"], response: "Ingat kenapa kamu mulai! Setiap langkah kecil itu berarti 💪✨" },
  { keywords: ["bisa", "pasti bisa", "yakin bisa", "harus bisa"], response: "Pasti bisa! Percaya pada dirimu sendiri! ✨💪" },
  { keywords: ["berhasil", "sukses", "success", "capai impian"], response: "Semangat mengejar impian! Sukses itu milik mereka yang pantang menyerah 🌟" },
  { keywords: ["impian", "cita-cita", "mimpi", "tujuan", "goal"], response: "Kejar terus impianmu! Setiap hari selangkah lebih dekat ke tujuan 🌟" },
  { keywords: ["gagal", "kegagalan", "failure", "mengalami kegagalan"], response: "Kegagalan bukan akhir, tapi awal dari sesuatu yang lebih baik! 💪" },
  { keywords: ["bangkit", "harus bangkit", "mau bangkit"], response: "Bangkit lagi! Orang yang sukses adalah yang bangkit satu kali lebih banyak dari jatuhnya 🌟" },
  { keywords: ["percaya diri", "kurang percaya diri", "ga pede", "gak pede", "pede"], response: "Percaya diri itu dilatih! Mulai dari hal kecil dan bertahap 😊💪" },
  { keywords: ["inspirasi", "inspiring", "menginspirasi", "terinspirasi"], response: "Semoga selalu terinspirasi! Jadilah inspirasi bagi orang lain juga 🌟" },
  { keywords: ["positive thinking", "positif", "pikiran positif", "berpikir positif"], response: "Positif thinking itu kekuatan! Pikiran positif menarik hal-hal positif 🌟" },
  { keywords: ["sabar", "bersabar", "harus sabar", "butuh kesabaran"], response: "Sabar ya, semua pasti ada waktunya! Rezeki tidak pernah tertukar 🙏" },
  { keywords: ["ikhtiar", "usaha", "berusaha", "terus usaha"], response: "Terus berikhtiar dan berdoa! Hasil tidak mengkhianati usaha 🙏💪" },

  // ─── AGAMA & DOA ─────────────────────────────────────────────────────────
  { keywords: ["alhamdulillah", "alhmadulillah", "alhamdulillahirobbilalamin"], response: "Alhamdulillah! Syukur selalu ya 🙏" },
  { keywords: ["insyaallah", "insyallah", "in sha allah", "insya allah"], response: "InsyaAllah! Semoga terkabul 🙏" },
  { keywords: ["subhanallah", "subhannallah", "masya allah", "masyaallah"], response: "MasyaAllah! Indah sekali 🙏" },
  { keywords: ["bismillah", "bismilah", "basmallah"], response: "Bismillah! Semoga dilancarkan 🙏" },
  { keywords: ["aamiin", "amin", "amiin", "aameen"], response: "Aamiin! 🙏 Semoga dikabulkan" },
  { keywords: ["doa", "doain", "minta doa", "doakan saya", "doain ya"], response: "Aamiin! Doa yang terbaik selalu menyertaimu 🙏" },
  { keywords: ["sholat", "solat", "shalat", "sudah sholat", "lupa sholat"], response: "Jangan lupa sholat ya! Ibadah itu kewajiban utama 🕌" },
  { keywords: ["puasa", "berpuasa", "lagi puasa", "sahur", "buka puasa"], response: "Semangat puasanya! Semoga ibadahnya diterima 🌙🙏" },
  { keywords: ["ramadhan", "bulan ramadan", "ramadan", "marhaban ya ramadhan"], response: "Marhaban ya Ramadhan! Semoga penuh berkah 🌙✨" },
  { keywords: ["lebaran", "idul fitri", "eid mubarak", "eid al fitr"], response: "Selamat Idul Fitri! Mohon maaf lahir dan batin 🙏🌙" },
  { keywords: ["idul adha", "eid adha", "qurban", "kurban"], response: "Selamat Idul Adha! Semoga ibadah qurbannya diterima 🙏" },
  { keywords: ["isra miraj", "isra' mi'raj"], response: "Selamat memperingati Isra Mi'raj! 🌙" },
  { keywords: ["natal", "merry christmas", "selamat natal", "selamat hari natal"], response: "Selamat Natal! Semoga penuh damai dan sukacita 🎄" },
  { keywords: ["tahun baru", "happy new year", "selamat tahun baru", "new year"], response: "Selamat Tahun Baru! Semoga tahun ini lebih baik 🎉✨" },
  { keywords: ["imlek", "tahun baru imlek", "gong xi fat cai", "kong xi fa cai"], response: "Gong Xi Fa Cai! Semoga penuh rejeki dan keberuntungan 🧧🎊" },
  { keywords: ["nyepi", "hari raya nyepi", "selamat nyepi"], response: "Selamat Hari Raya Nyepi! 🙏" },
  { keywords: ["waisak", "hari waisak", "selamat waisak"], response: "Selamat Hari Waisak! Semoga penuh kedamaian ✨" },
  { keywords: ["hari kemerdekaan", "17 agustus", "dirgahayu Indonesia", "HUT RI", "merdeka"], response: "MERDEKA! Dirgahayu Republik Indonesia! 🇮🇩🎉" },

  // ─── TEKNOLOGI & GADGET ───────────────────────────────────────────────────
  { keywords: ["hp", "handphone", "smartphone", "telepon", "ponsel"], response: "HP apa yang dipakai? Ada yang mau ditanyain soal HP? 📱" },
  { keywords: ["laptop", "notebook", "komputer", "PC", "desktop"], response: "Laptop/PC apa yang dipakai? Spek-nya gimana? 💻" },
  { keywords: ["charger", "cas", "baterai habis", "lowbat", "low battery"], response: "Aduh lowbat! Cepat cas dulu biar ga ketinggalan apa-apa 🔋" },
  { keywords: ["wifi", "internet", "koneksi internet", "sinyal"], response: "Soal internet, pastikan sinyal kuat ya biar lancar! 📶" },
  { keywords: ["aplikasi", "app", "apk", "install", "download"], response: "Mau install aplikasi apa? Pastikan dari sumber terpercaya ya! 📲" },
  { keywords: ["update aplikasi", "update app", "versi terbaru app"], response: "Segera update aplikasinya biar dapat fitur terbaru! 🆕" },
  { keywords: ["storage", "memori penuh", "storage penuh", "kapasitas penuh"], response: "Storage penuh? Saatnya bersih-bersih file yang tidak perlu! 🗂️" },
  { keywords: ["password", "lupa password", "reset password", "ganti password"], response: "Lupa password? Coba opsi 'Forgot Password' atau reset via email ya 🔐" },
  { keywords: ["akun", "login", "masuk akun", "buat akun", "daftar"], response: "Soal akun, pastikan data pribadi aman ya! 🔐" },
  { keywords: ["hack", "kena hack", "akun di-hack", "hacked"], response: "Wah kena hack? Segera ganti password dan aktifkan 2FA! 🔒" },
  { keywords: ["virus", "malware", "kena virus", "laptop kena virus"], response: "Ada virus? Segera scan dengan antivirus terpercaya ya! 🛡️" },
  { keywords: ["coding", "ngoding", "programming", "belajar coding"], response: "Coding itu seru! Lagi belajar bahasa pemrograman apa? 💻" },
  { keywords: ["javascript", "python", "java", "php", "css", "html", "react", "vue"], response: "Wah programmer nih! Lagi ngerjain project apa? 💻🔥" },
  { keywords: ["website", "web", "bikin website", "buat website"], response: "Bikin website! Mau pakai teknologi apa? 🌐" },
  { keywords: ["database", "mysql", "postgresql", "mongodb", "firebase"], response: "Database! Pilihan yang digunakan tergantung kebutuhan ya 💾" },
  { keywords: ["cloud", "aws", "google cloud", "azure", "server"], response: "Cloud computing sekarang sudah jadi kebutuhan ya! ☁️" },

  // ─── PENDIDIKAN ────────────────────────────────────────────────────────────
  { keywords: ["SD", "SMP", "SMA", "SMK", "sekolah menengah"], response: "Semangat sekolah! Ini waktu yang berharga untuk belajar 📚" },
  { keywords: ["kuliah", "mahasiswa", "mahasiswi", "kampus", "universitas"], response: "Semangat kuliah! Nikmati masa-masa ini ya 🎓" },
  { keywords: ["skripsi", "thesis", "tesis", "sidang", "wisuda"], response: "Semangat skripsi/tesis! Pasti lulus dengan nilai terbaik 💪🎓" },
  { keywords: ["bimbingan", "dospem", "dosen pembimbing", "revisi skripsi"], response: "Sabar menghadapi revisi ya! Prosesnya memang panjang tapi hasilnya worth it 💪" },
  { keywords: ["ospek", "MOS", "orientasi", "masa pengenalan"], response: "Semangat ospek! Enjoy prosesnya ya, banyak teman baru yang bisa didapat 😊" },
  { keywords: ["beasiswa", "scholarship", "dana pendidikan"], response: "Hunting beasiswa keren! Banyak kesempatan di luar sana untuk kamu 🌟" },
  { keywords: ["IPK", "GPA", "nilai", "nilai bagus", "nilai jelek"], response: "IPK bukan segalanya, tapi tetap berusaha maksimal ya! 📊" },
  { keywords: ["UTS", "UAS", "ujian tengah semester", "ujian akhir semester"], response: "Semangat menghadapi ujian! Belajar yang baik, istirahat cukup 📖💪" },
  { keywords: ["contek", "nyontek", "curang ujian", "copas tugas"], response: "Jangan nyontek ya! Lebih baik hasil sendiri meski kurang sempurna 📝" },
  { keywords: ["presentasi", "sidang", "defense", "maju presentasi"], response: "Semangat presentasi! Percaya diri dan kuasai materinya 💪" },

  // ─── KARIR & PEKERJAAN ────────────────────────────────────────────────────
  { keywords: ["cari kerja", "job hunting", "lowongan kerja", "kerja apa", "mau kerja"], response: "Semangat job hunting! Persiapkan CV yang baik dan tetap percaya diri 💼💪" },
  { keywords: ["interview", "wawancara", "mau interview", "jadwal interview"], response: "Semangat interview! Pelajari perusahaannya dan persiapkan jawaban 💪" },
  { keywords: ["CV", "resume", "daftar riwayat hidup", "bikin CV"], response: "CV yang baik itu singkat, padat, dan relevan! Tonjolkan pengalaman terbaik ya 📄" },
  { keywords: ["resign", "keluar kerja", "mau resign", "sudah resign"], response: "Resign? Pastikan sudah ada rencana selanjutnya ya! 💼" },
  { keywords: ["fresh graduate", "freshgrad", "lulusan baru", "baru lulus"], response: "Fresh graduate! Semangat memulai karir! Jangan patah semangat meski sulit di awal 💪" },
  { keywords: ["magang", "internship", "PKL", "praktik kerja lapangan"], response: "Magang! Manfaatkan waktu ini untuk belajar sebanyak mungkin 📚💼" },
  { keywords: ["freelance", "freelancer", "kerja freelance", "project freelance"], response: "Freelance! Enak bisa kerja bebas! Tapi tetap disiplin ya manajemen waktunya 💻" },
  { keywords: ["startup", "bisnis startup", "join startup"], response: "Startup! Penuh tantangan tapi seru! Siap belajar banyak hal 🚀" },
  { keywords: ["wirausaha", "entrepreneur", "bisnis sendiri", "mau bisnis"], response: "Semangat berbisnis! Konsisten dan terus belajar adalah kunci sukses 🚀" },
  { keywords: ["WFH vs WFO", "enak WFH", "enak WFO", "mending WFH"], response: "WFH vs WFO tergantung preferensi masing-masing! Keduanya punya kelebihan sendiri 😊" },

  // ─── GAUL & SLANG TERKINI ─────────────────────────────────────────────────
  { keywords: ["baper", "baperr", "baperan", "gampang baper"], response: "Hehe jangan baper ya! 😄" },
  { keywords: ["mager", "lagi mager", "males gerak"], response: "Mager itu godaan terbesar! 😅 Ayo gerak dikit!" },
  { keywords: ["bodo amat", "bodoh amat", "gapeduli", "cuek aja"], response: "Wkwk bodo amat! Tapi jangan kebanyakan apatis ya 😅" },
  { keywords: ["gercep", "gerakan cepat", "gerak cepat"], response: "Gercep! Nggak mau ketinggalan nih! 🏃💨" },
  { keywords: ["elap", "kuas", "lap lap"], response: "Haha iya lap dulu! 😄" },
  { keywords: ["ciyus", "serius", "ciyus miapah"], response: "Wkwk ciyus! Nostalgia bahasa gaul lama! 😄" },
  { keywords: ["alay", "alayyy", "gaya alay", "tulisan alay"], response: "Jangan terlalu alay! Hehe tapi gapapa asalkan tidak berlebihan 😄" },
  { keywords: ["selo", "selo banget", "santai banget", "relaks banget"], response: "Selo! Enak banget ya hidupnya 😎" },
  { keywords: ["ngehek", "ngeheks", "aneh banget", "heran bgt"], response: "Wkwk ngehek emang! 😄" },
  { keywords: ["julidan", "nyinyiran", "nyinyir terus"], response: "Jangan nyinyir terus ya! Fokus ke kebaikan masing-masing 😊" },
  { keywords: ["mainnya", "gaul banget", "pergaulan luas"], response: "Gaul emang penting! Tapi tetap selektif pilih lingkungan ya 😊" },
  { keywords: ["okelah kalau begitu", "oke kalau gitu", "okeh kalau begitu"], response: "Oke kalau gitu! Hehe 😄" },
  { keywords: ["ntar aja", "besok aja", "entar aja", "kapan-kapan aja"], response: "Jangan nunda-nunda terus! Sekarang lebih baik dari nanti 😄" },
  { keywords: ["kelamaan", "lama bgt", "terlalu lama", "so slow"], response: "Sabar ya! Proses yang baik butuh waktu 😊" },
  { keywords: ["langsung aja", "to the point", "langsung to the point"], response: "Oke langsung to the point! Mau apa? 😄" },
  { keywords: ["awkward", "canggung", "kikuk", "ga enak badan"], response: "Haha awkward moment! 😅 Santai aja!" },
  { keywords: ["cringe", "cring", "memalukan", "malu banget"], response: "Wkwk cringe banget ya! 😅" },
  { keywords: ["savage", "jleb", "nyelekit", "kata-kata jleb"], response: "Savage banget! 🔥 Jleb langsung!" },
  { keywords: ["on point", "tepat banget", "kena banget", "relate banget"], response: "On point banget! Relate 100%! 🎯" },
  { keywords: ["bestie", "bestii", "best friend", "sahabat", "teman dekat"], response: "Bestie emang paling mantap! 💙 Lucky punya teman kayak gitu!" },
  { keywords: ["squad", "geng", "genk", "teman-teman"], response: "Squad goals! Semangat bareng-bareng 🤝" },
  { keywords: ["no cap", "fr fr", "real talk", "jujur nih"], response: "No cap! Iya serius nih 😄" },
  { keywords: ["slay", "slayy", "killing it", "gaskeun"], response: "SLAY! Kamu emang keren! 🔥" },
  { keywords: ["lowkey", "quietly", "diem-diem"], response: "Lowkey keren tuh! 😎" },
  { keywords: ["highkey", "sangat jelas", "udah jelas"], response: "Highkey setuju! 😄" },
  { keywords: ["vibe check", "vibes nih", "vibes bagus"], response: "Vibe check: PASSED! ✅😄" },
  { keywords: ["rent free", "rent-free", "kepikiran terus", "ga bisa lupa"], response: "Living rent free di kepala wkwk! 😄" },
  { keywords: ["it's giving", "its giving", "vibes-nya", "nuansanya"], response: "It's giving energy yang keren! 🌟" },
  { keywords: ["understood the assignment", "nangkep maksudnya", "paham tugasnya"], response: "Understood the assignment! 🎯✅" },
  { keywords: ["we don't talk about", "ga usah dibahas", "lupain aja"], response: "Wkwk we don't talk about it 😅" },
  { keywords: ["delulu", "delusion", "delulu bgt", "ga realistis"], response: "Jangan terlalu delulu ya! Tapi boleh sedikit positif 😄" },
  { keywords: ["rizz", "rizzy", "rizz bgt", "punya rizz"], response: "Rizz! Karisma-nya keluar! 😎✨" },
  { keywords: ["mid", "biasa aja", "ga spesial", "average"], response: "Mid ya? Hehe, bisa ditingkatin lagi kok! 😊" },
  { keywords: ["based", "factual", "real", "berdasarkan fakta"], response: "Based! Setuju banget! 💯" },
  { keywords: ["sigma", "sigma male", "sigma grindset"], response: "Sigma grindset! Terus tingkatkan diri! 💪" },
  { keywords: ["alpha", "alpha male", "jadi alpha"], response: "Alpha vibes! Percaya diri dan terus berkembang 💪" },
  { keywords: ["glow up", "glowup", "berubah jadi lebih baik"], response: "Glow up yang nyata! Keren banget perubahannya! ✨" },
  { keywords: ["plot twist", "plottwist", "twist cerita", "ga terduga"], response: "PLOT TWIST! 😱 Ga nyangka!" },
  { keywords: ["era baru", "new era", "babak baru"], response: "Era baru dimulai! Semangat jalani 🌟" },
  { keywords: ["main character", "main karakter", "energy main character"], response: "Main character energy! You are the protagonist of your own story! 🌟" },
  { keywords: ["npc", "NPC", "seperti npc", "kayak npc"], response: "Wkwk jangan jadi NPC! Jadilah main character hidupmu! 😄" },
  { keywords: ["lore", "lore-nya", "backstory", "cerita latar"], response: "Lore-nya dalam banget! Cerita lebih dong! 😄" },
  { keywords: ["canon event", "canon nih", "sudah takdir", "memang harusnya begitu"], response: "Canon event! Semua udah digariskan! 😄" },
  { keywords: ["down bad", "down bad bgt", "desperate"], response: "Wkwk down bad! Jaga harga diri ya! 😅" },
  { keywords: ["ate", "ate that", "killing it", "nailed it"], response: "You ATED that! 🔥 Keren banget!" },
  { keywords: ["the way", "the way dia", "one thing about"], response: "Iya the way itu! 😄 Emang gitu banget!" },
  { keywords: ["pop off", "popoff", "go off", "gasss"], response: "POP OFF! LET HIM/HER COOK! 🔥" },
  { keywords: ["periodt", "period", "full stop", "titik"], response: "PERIODT! 💅 Final answer!" },
  { keywords: ["sis", "queen", "king", "boss"], response: "You're the queen/king! 👑" },
  { keywords: ["tea", "spill the tea", "gossip", "gosip"], response: "Spill the tea! Mau cerita apa? 🍵😏" },
  { keywords: ["shade", "throw shade", "sindir", "nyindir"], response: "Jangan terlalu banyak throw shade ya! 😅" },
  { keywords: ["finesse", "berhasil nipu", "sukses akali"], response: "Finesse! Hehe tapi jangan sampai ngelanggar etika ya! 😄" },

  // ─── EKSPRESI TAMBAHAN ────────────────────────────────────────────────────
  { keywords: ["hmm", "hmmm", "hmmmm", "mikir dulu", "bentar"], response: "Hmm, ada yang mau dipikirkan? Boleh tanya aja! 😊" },
  { keywords: ["oh", "ooh", "ohh", "ohhh", "oh gitu", "oh iya"], response: "Oh ya! Ada yang mau ditanyain lebih lanjut? 😊" },
  { keywords: ["ah", "ahh", "ahhh", "ah iya", "ah gitu"], response: "Ah iya! Ada lagi yang mau dibahas? 😊" },
  { keywords: ["eh iya", "iya sih", "bener juga", "bener juga sih"], response: "Iya bener juga! 😄" },
  { keywords: ["asyik", "asikk", "asyikk", "seru bgt"], response: "Asyik banget! Ada cerita seru apa nih? 😄" },
  { keywords: ["seru", "seruu", "seruuu", "seru bgt", "seru banget"], response: "Seru! Cerita lebih dong! 😄" },
  { keywords: ["nais", "nice", "nicee", "niceee", "good job", "good"], response: "Nice! Bagus banget! 👍😄" },
  { keywords: ["perfect", "sempurna", "flawless", "without flaw"], response: "Perfect! Sempurna banget! 🌟" },
  { keywords: ["wow banget", "amazing bgt", "luar biasa bgt", "the best"], response: "Amazing! Keren banget beneran! 🌟🔥" },
  { keywords: ["biasa aja", "biasa doang", "ga istimewa", "standard"], response: "Wkwk biasa aja ya? Tapi gapapa, bisa ditingkatkan! 😊" },
  { keywords: ["hadeh", "haduh", "aduh", "aduhhh"], response: "Aduh ada apa? Cerita dong! 😊" },
  { keywords: ["meh", "so so", "standar", "not bad"], response: "Meh ya? Semoga bisa lebih baik lagi 😊" },
  { keywords: ["bruh", "bruhhh", "bro serius", "bro nih"], response: "Bruh 😅 Ada apa emangnya?" },
  { keywords: ["buset", "buset dah", "buset bro"], response: "Buset! Ada apa emangnya? 😮" },
  { keywords: ["asem", "ajaib", "aneh", "ga biasa"], response: "Wkwk aneh-aneh aja! 😄" },
  { keywords: ["tapi kan", "tapikan", "tapi ya", "padahal kan"], response: "Tapi? Lanjutin ceritanya! 😊" },
  { keywords: ["soalnya", "karena", "sebabnya", "alasannya"], response: "Apa alasannya? Cerita dong! 😊" },
  { keywords: ["mending", "lebih baik", "mungkin lebih baik", "mendingan"], response: "Mending mana ya? Tergantung situasinya! 😊" },
  { keywords: ["emangnya", "emang", "memangnya", "sebenernya"], response: "Emangnya gimana? Cerita lebih detail dong! 😊" },
  { keywords: ["gimana pun", "bagaimanapun", "anyway", "anyways"], response: "Anyways, ada yang bisa dibantu? 😊" },
  { keywords: ["fyi", "note", "catatan", "perlu diketahui"], response: "Oke noted! Terima kasih infonya 📝" },
  { keywords: ["update", "ada update", "kabar terbaru", "berita terbaru"], response: "Update terbaru nih! Ada info apa? 📰" },
  { keywords: ["breaking news", "berita baru", "baru tau"], response: "Breaking news! Apa yang terjadi? 📢" },

  // ─── RESPON KHUSUS ────────────────────────────────────────────────────────
  { keywords: ["cinta", "sayang", "love", "aku cinta kamu", "aku sayang kamu"], response: "Aww, manis sekali! 🥰 Tapi aku cuma bot ya hehe" },
  { keywords: ["nikah", "kawin", "menikah", "mau nikah", "lamaran"], response: "Wah mau nikah! Selamat ya, semoga langgeng dan barokah 💍🙏" },
  { keywords: ["pacaran", "jadian", "resmi pacaran", "udah jadian"], response: "Wah jadian! Selamat! Semoga awet dan bahagia 💑❤️" },
  { keywords: ["ulang tahun", "happy birthday", "HBD", "hbd ya", "ultah"], response: "HAPPY BIRTHDAY! 🎂🎉 Semoga sehat, bahagia, dan semua impiannya terwujud! 🌟🎁" },
  { keywords: ["anniversary", "ulang tahun hubungan", "selamatan"], response: "Happy Anniversary! Semoga terus bahagia dan semakin langgeng 💑🎉" },
  { keywords: ["lulus", "kelulusan", "wisuda", "sudah lulus"], response: "SELAMAT LULUS/WISUDA! 🎓🎉 Perjuanganmu selama ini terbayar sudah!" },
  { keywords: ["hamil", "mengandung", "berbadan dua", "mau punya anak"], response: "Selamat ya! Semoga proses kehamilan lancar dan sehat 🤱💙" },
  { keywords: ["melahirkan", "baru melahirkan", "punya anak baru", "lahiran"], response: "Selamat atas kelahiran si kecil! Semoga menjadi anak yang sholeh/sholehah 👶💙" },
  { keywords: ["pindah rumah", "pindahan", "rumah baru", "kontrakan baru"], response: "Selamat pindah rumah baru! Semoga betah dan nyaman di tempat baru 🏠😊" },
  { keywords: ["kena musibah", "musibah", "kecelakaan", "sakit parah", "duka"], response: "Innalillahi, turut berduka. Semoga diberi ketabahan dan kekuatan 🙏" },
  { keywords: ["meninggal", "wafat", "almarhum", "almarhumah", "innalillahi"], response: "Innalillahi wa inna ilaihi raji'un. Turut berbela sungkawa yang sedalam-dalamnya 🙏" },
  { keywords: ["sembuh", "sudah sembuh", "sudah sehat", "pulih"], response: "Alhamdulillah sudah sembuh! Jaga kesehatan terus ya 😊🙏" },
  { keywords: ["terima kasih sudah ada", "makasih selalu ada", "ada saat dibutuhkan"], response: "Sama-sama! Aku selalu siap ada buat kamu kapanpun 😊💙" },

  // ─── PERTANYAAN ISENG ─────────────────────────────────────────────────────
  { keywords: ["1+1", "1 + 1", "berapa 1+1", "satu tambah satu"], response: "1+1 = 2! Wkwk 😄" },
  { keywords: ["7 x 8", "7x8", "tujuh kali delapan"], response: "7 x 8 = 56! 😄" },
  { keywords: ["bumi bulat", "bumi datar", "flat earth"], response: "Bumi itu bulat ya, sudah terbukti secara ilmiah! 🌍" },
  { keywords: ["ayam dulu atau telur", "telur dulu atau ayam"], response: "Pertanyaan klasik! Secara evolusi, telur datang lebih dulu 🥚🐔😄" },
  { keywords: ["kenapa langit biru", "langit itu biru", "warna langit"], response: "Langit biru karena fenomena Rayleigh scattering — cahaya biru menyebar lebih banyak! 🌤️" },
  { keywords: ["tebak-tebakan", "tebak", "mau tebak-tebakan"], response: "Boleh! Apa yang mau ditebak? 😄" },
  { keywords: ["siapa presiden indonesia", "presiden sekarang", "presiden RI"], response: "Untuk informasi terkini soal presiden, cek berita terpercaya ya! 📰" },
  { keywords: ["apa itu love", "love itu apa", "cinta itu apa", "arti cinta"], response: "Cinta itu... perasaan mendalam yang membuat kita peduli tanpa syarat 💙😊" },
  { keywords: ["hidup itu apa", "arti hidup", "makna kehidupan"], response: "Hidup itu anugerah! Maknanya kita yang tentukan sendiri melalui pilihan dan tindakan kita 🌟" },
  { keywords: ["apa itu sukses", "sukses itu apa", "definisi sukses"], response: "Sukses itu berbeda bagi setiap orang. Tapi intinya: mencapai tujuan yang bermakna bagimu! 🌟" },

  // ─── BAHASA DAERAH / REGIONAL ─────────────────────────────────────────────
  { keywords: ["punten", "punten kang", "punten aa"], response: "Mangga, aya naon? 😊 (Silakan, ada apa?)" },
  { keywords: ["kumaha", "kumaha damang", "kumaha abar"], response: "Damang, hatur nuhun! 😊 (Sehat, terima kasih!)" },
  { keywords: ["hatur nuhun", "hapunten", "nuhun"], response: "Sami-sami! 😊 (Sama-sama!)" },
  { keywords: ["piye kabare", "piye kabar", "kabar piye"], response: "Apik-apik wae! Matur nuwun! 😊 (Baik-baik saja, terima kasih!)" },
  { keywords: ["matur nuwun", "maturnuwun", "nuwun"], response: "Sami-sami nggih! 😊 (Sama-sama ya!)" },
  { keywords: ["opo kabar", "kabar opo", "piye kabari"], response: "Apik mbak/mas! 😊 Ada yang bisa dibantu?" },
  { keywords: ["dari mana asal", "orang mana", "asalnya dari mana", "asli mana"], response: "Aku dari mana-mana! Hehe, bot ga punya asal 😄 Kamu dari mana?" },
  { keywords: ["orang jakarta", "orang jawa", "orang sunda", "orang batak", "orang mana"], response: "Semua daerah keren! Indonesia penuh keberagaman yang indah 🇮🇩" },
  { keywords: ["bahasa jawa", "ngomong jawa", "bisa jawa"], response: "Sedikit ngerti bahasa Jawa! Hehe ngapunten kalau kurang tepat 😊" },
  { keywords: ["bahasa sunda", "ngomong sunda", "bisa sunda"], response: "Ngerti sedikit bahasa Sunda! Kumaha damang? 😊" },
  { keywords: ["bahasa batak", "ngomong batak"], response: "Horas! Semangat ya! 😊" },
  { keywords: ["horas", "horas bah"], response: "Horas! Semoga selalu sehat dan sukses! 🙏😊" },
  { keywords: ["yo wes", "yo wis", "ya wes", "ya wis"], response: "Yo wes! Oke deh! 😄" },
  { keywords: ["lur", "lelur", "dulur"], response: "Halo dulur! Ada apa? 😄" },
  { keywords: ["woi", "woyy", "woi bro", "woiii"], response: "Woi! Ada apa bro? 😄" },

  // ─── TAMBAHAN MASIF VARIASI KATA ──────────────────────────────────────────
  { keywords: ["nanti sore", "ntar sore", "sore nanti", "entar sore"], response: "Oke, nanti sore! Ada rencana apa? 😊" },
  { keywords: ["besok", "besoknya", "hari besok", "hari ini besok"], response: "Oke, besok ya! Ada yang perlu dipersiapkan? 😊" },
  { keywords: ["kemarin", "kemarinnya", "hari kemarin"], response: "Kemarin ada apa? Cerita dong! 😊" },
  { keywords: ["tadi", "barusan", "baru aja", "sebentar lagi"], response: "Baru aja? Gimana hasilnya? 😊" },
  { keywords: ["sekarang", "saat ini", "right now", "now"], response: "Sekarang nih! Ada yang perlu dibantu segera? 😊" },
  { keywords: ["ntar malam", "malam ini", "malam nanti", "tonight"], response: "Malam ini ada rencana apa? 😊" },
  { keywords: ["weekend", "akhir minggu", "sabtu minggu", "libur"], response: "Weekend! Rencana ngapain akhir minggu ini? 😄" },
  { keywords: ["senin", "monday", "awal minggu", "mulai kerja"], response: "Senin! Semangat memulai minggu baru! 💪" },
  { keywords: ["jumat", "friday", "jumat lagi", "akhirnya jumat"], response: "TGIF! Finally Friday! 🎉" },
  { keywords: ["tanggal merah", "libur nasional", "hari libur", "cuti"], response: "Tanggal merah! Saatnya recharge energi 😊🎉" },
  { keywords: ["liburan sekolah", "musim liburan", "school holiday"], response: "Liburan sekolah! Saatnya menikmati waktu bersama keluarga 😊" },
  { keywords: ["mudik", "pulang kampung", "balik kampung"], response: "Mudik! Semangat pulang kampung, hati-hati di jalan ya! 🚗" },
  { keywords: ["macet", "kemacetan", "terjebak macet", "stuck macet"], response: "Aduh macet ya! Sabar aja, sambil dengerin musik biar ga bosen 🎵" },
  { keywords: ["hujan", "lagi hujan", "ujan", "ujan deras", "banjir"], response: "Hujan! Hati-hati di jalan ya, dan jangan lupa bawa payung 🌧️☂️" },
  { keywords: ["panas", "gerah", "cuaca panas", "terik"], response: "Panas banget ya! Minum air putih yang banyak biar ga dehidrasi 💧" },
  { keywords: ["angin", "angin kencang", "banjir angin"], response: "Angin kencang ya! Hati-hati di luar, stay safe 🌬️" },
  { keywords: ["gempa", "gempa bumi", "terjadi gempa"], response: "Semoga semua baik-baik saja! Stay safe dan ikuti prosedur evakuasi 🙏" },
  { keywords: ["bencana", "bencana alam", "keadaan darurat"], response: "Turut prihatin atas bencana yang terjadi. Semoga semua selamat 🙏" },
  { keywords: ["nongkrong", "nongkrong yuk", "mau nongkrong", "ngopi bareng"], response: "Nongkrong asik! Dimana? 😄" },
  { keywords: ["kongkow", "kongkow dulu", "kumpul dulu", "kumpul yuk"], response: "Kongkow! Seru nih kumpul-kumpul! 😄" },
  { keywords: ["karaoke", "mau karaoke", "karaoke yuk"], response: "Karaoke! Seru banget! Lagu wajib apa yang harus dinyanyiin? 🎤" },
  { keywords: ["bioskop", "nonton bioskop", "mau bioskop", "film apa yang tayang"], response: "Bioskop! Film apa yang mau ditonton? 🎬" },
  { keywords: ["mall", "mal", "pergi ke mall", "jalan-jalan mall"], response: "Ke mall! Jangan kalap belanja ya hehe 😄🛍️" },
  { keywords: ["kafe", "cafe", "ngopi di kafe", "ke kafe"], response: "Kafe hits mana yang mau dikunjungi? ☕😄" },
  { keywords: ["restoran", "restaurant", "makan di restoran", "resto"], response: "Makan di restoran! Jenis masakan apa yang diinginkan? 🍽️" },
  { keywords: ["warteg", "warung makan", "mie ayam", "bakso", "soto", "gado-gado"], response: "Makan makanan Indonesia! Enak dan murah meriah 😄🍜" },
  { keywords: ["gofood", "grabfood", "shopeefood", "order makanan", "pesan online"], response: "Order online! Makanan favorit apa yang dipesan? 🛵🍱" },
  { keywords: ["gojek", "grab", "ojol", "ojek online"], response: "Ojol! Praktis banget ya transportasi zaman sekarang 🛵" },
  { keywords: ["commuter line", "KRL", "MRT", "busway", "transjakarta"], response: "Transportasi umum! Lebih ramah lingkungan dan anti macet 🚊" },
  { keywords: ["kemacetan jakarta", "macet jakarta", "ibukota macet"], response: "Macet Jakarta memang legendaris! 😅 Hati-hati dan sabar ya!" },
  { keywords: ["IKN", "ibu kota nusantara", "pindah ibu kota", "ibukota baru"], response: "IKN! Proyek besar yang menarik ya! Semoga sukses 🏙️🌿" },
  { keywords: ["politik", "pemilu", "pilkada", "pilpres", "partai"], response: "Soal politik, bijak dalam memilih dan jangan mudah terprovokasi ya! 🗳️" },
  { keywords: ["korupsi", "anti korupsi", "kasus korupsi"], response: "Anti korupsi! Semoga bangsa kita semakin bersih dari korupsi 🙏" },
  { keywords: ["hukum", "aturan", "undang-undang", "peraturan"], response: "Soal hukum, sebaiknya konsultasi dengan ahli hukum ya untuk kepastian 📜" },
  { keywords: ["berita hoaks", "hoax", "info palsu", "cek fakta"], response: "Hati-hati hoaks! Selalu cek fakta dari sumber terpercaya sebelum share 🔍" },
  { keywords: ["media sosial negatif", "efek negatif sosmed", "toxic social media"], response: "Bijak dalam penggunaan media sosial ya! Pilih konten yang positif 😊" },
  { keywords: ["kesehatan mental", "mental health", "mental well-being", "psikolog"], response: "Kesehatan mental itu penting! Jangan ragu mencari bantuan profesional jika perlu 💙" },
  { keywords: ["depresi", "depression", "anxiety", "gangguan kecemasan"], response: "Jika kamu atau seseorang yang kamu kenal membutuhkan bantuan, hubungi profesional kesehatan mental ya 🙏" },
  { keywords: ["meditasi", "meditation", "yoga", "mindfulness"], response: "Meditasi dan mindfulness itu bagus untuk kesehatan mental! Coba rutinkan ya 🧘" },
  { keywords: ["self care", "perawatan diri", "sayangi diri", "love yourself"], response: "Self care itu penting! Jangan lupa merawat diri ya 🌸" },
  { keywords: ["produktif", "produktivitas", "cara produktif", "lebih produktif"], response: "Kunci produktivitas: fokus, manajemen waktu, dan istirahat yang cukup! 💪" },
  { keywords: ["manajemen waktu", "time management", "atur waktu"], response: "Time management yang baik bisa mengubah hidup! Coba buat jadwal dan patuhi 📅" },
  { keywords: ["buku self improvement", "buku motivasi", "rekomendasi buku"], response: "Buku self-improvement yang bagus banyak! Mulai dari 'Atomic Habits' hingga '7 Habits' 📚" },
  { keywords: ["podcast bagus", "podcast motivasi", "rekomendasi podcast"], response: "Podcast bagus banyak ya! Tergantung minatmu, dari bisnis, teknologi, hingga mindset 🎙️" },
  { keywords: ["youtube channel bagus", "youtuber favorit", "channel youtube rekomendasi"], response: "Channel YouTube bagus banyak! Sesuaikan dengan minat dan kebutuhanmu 📺" },
  { keywords: ["netflix", "disney plus", "streaming", "binge watch"], response: "Streaming memang bikin nagih! Jangan sampai lupa tidur ya 😄📺" },
  { keywords: ["anime", "nonton anime", "anime apa", "weeb"], response: "Anime fans! 🎌 Anime favorit apa yang lagi ditonton?" },
  { keywords: ["manga", "baca manga", "komik jepang"], response: "Manga! Genre apa yang suka dibaca? 📚" },
  { keywords: ["kdrama", "drakor", "nonton drakor", "korean drama"], response: "Drakor selalu bikin baper! 😄 Lagi nonton drama apa?" },
  { keywords: ["kpop", "K-pop", "bts", "blackpink", "aespa", "twice"], response: "K-Pop! Fandom apa yang kamu ikuti? 🎵✨" },
  { keywords: ["idol", "bias", "oshi", "favorite member"], response: "Siapa biasnya? 😄✨" },
  { keywords: ["konser", "concert", "mau ke konser", "tiket konser"], response: "Konser! Artis siapa yang mau ditonton? 🎤🎉" },
  { keywords: ["festival musik", "music festival", "fest", "event musik"], response: "Festival musik! Seru banget! Sudah beli tiketnya? 🎵🎉" },

  // ─── PENUTUP MASIF ────────────────────────────────────────────────────────
  { keywords: ["sudah cukup", "cukup ya", "segitu aja", "udah itu aja"], response: "Oke, sudah cukup! Senang bisa membantu. Sampai jumpa! 😊👋" },
  { keywords: ["terimakasih sudah menjawab", "makasih udah jawab", "thanks for answering"], response: "Sama-sama! Senang bisa menjawab pertanyaanmu 😊" },
  { keywords: ["puas dengan jawabannya", "jawaban memuaskan", "jawaban oke"], response: "Senang bisa membantu! Kalau ada pertanyaan lain, jangan ragu ya 😊" },
  { keywords: ["ada lagi", "ada yang lain", "mau tanya lagi", "masih ada"], response: "Iya, ada apa lagi? Saya siap membantu! 😊" },
  { keywords: ["hanya itu", "itu saja", "cuma itu", "hanya ini"], response: "Oke! Kalau ada yang perlu ditanyain lagi, tanya saja ya! 😊" },
  { keywords: ["lain kali", "nanti lagi", "kapan-kapan", "next time"], response: "Oke, lain kali! Aku selalu siap kapan saja 🤖😊" },
  { keywords: ["sampai sini dulu", "cukup sampai sini", "stop dulu"], response: "Oke, sampai di sini dulu! Semoga semua informasinya bermanfaat 😊" },
  { keywords: ["thanks sudah dengerin", "makasih udah dengerin", "thanks for listening"], response: "Sama-sama! Aku selalu siap dengerin kamu 💙" },
  { keywords: ["have a great day", "have a nice day", "selamat beraktivitas", "semoga harinya baik"], response: "You too! Selamat beraktivitas, semoga hari ini penuh hal-hal positif! ☀️😊" },
  { keywords: ["keep smiling", "tetap senyum", "jaga senyum"], response: "Keep smiling! Senyummu bisa mencerahkan hari orang lain 😊✨" },
  { keywords: ["stay safe", "jaga keselamatan", "hati-hati", "jaga diri"], response: "Stay safe! Jaga kesehatan dan keselamatan selalu ya 🙏" },
  { keywords: ["love you", "i love you", "luv u", "ily"], response: "Aww, so sweet! 🥰 Semoga dibalas oleh orang yang tepat ya hehe!" },
  { keywords: ["hate you", "i hate you", "aku benci kamu", "gak suka kamu"], response: "Aduh, ada apa? Walaupun begitu, aku tetap siap membantu lho! 😊" },
  { keywords: ["kamu paling baik", "lo paling baik", "elu paling ok", "terbaik"], response: "Aww, makasih ya! Berusaha yang terbaik selalu! 😊💙" },
  { keywords: ["aku kangen kamu", "gue kangen lo", "miss you", "i miss you"], response: "Miss you too! Hehe, aku selalu di sini kapanpun dibutuhkan 😊" },
  { keywords: ["chatting terus", "ngobrol terus", "ga bosen ngobrol"], response: "Hehe senang ngobrol juga! Chatting terus aja ya, aku selalu siap 😄" },
  { keywords: ["seru ngobrol sama kamu", "enak ngobrol", "asyik ngobrol"], response: "Senang bisa ngobrol sama kamu juga! 😊 Kapanpun mau ngobrol, sini aja!" },
  { keywords: ["aku percaya kamu", "percaya sama kamu", "trust you"], response: "Makasih kepercayaannya! Aku akan selalu berusaha memberikan info yang akurat 😊" },
  { keywords: ["aku selalu chat kamu", "sering chat sini", "langganan chat sini"], response: "Hehe, aku juga senang! Selalu siap kapanpun kamu mau ngobrol 🤖😊" },
];

export default autoResponder;

/**
 * Cara penggunaan:
 *
 * import autoResponder from './auto-responder-index.js';
 *
 * function getResponse(userInput) {
 *   const input = userInput.toLowerCase().trim();
 *   for (const entry of autoResponder) {
 *     if (entry.keywords.some(kw => input.includes(kw))) {
 *       return entry.response;
 *     }
 *   }
 *   return "Maaf, saya tidak mengerti maksud kamu. Bisa diulang dengan kalimat lain? 😊";
 * }
 */
